FROM postgres:9.6-alpine
LABEL maintainer='Andreas Roither <this@andreasroither.at>'

ADD create-database.sh /docker-entrypoint-initdb.d/create-database.sh
RUN chmod +x /docker-entrypoint-initdb.d/create-database.sh