FROM openjdk:8-jre-alpine 
LABEL maintainer='Andreas Roither <this@roither.at>' 
EXPOSE 8080 
ARG VERSION=latest 
ADD continuousdelivery-${VERSION}-exec.jar /opt/app/app.jar 
#CMD ["java", "-jar", "/opt/app/app.jar"]
CMD java -jar /opt/app/app.jar